### students verifyIfHasCertification
POST http://localhost:8085/students/verifyIfHasCertification
Content-Type: application/json

{
  "email": "rudolfhiok@email.com",
  "technology": "JAVA"
}

### questions listByTechnology
GET http://localhost:8085/questions/technology/JAVA
