## Test Hello NLW
GET http://localhost:3333/hello


### Create poll
POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "Qual a melhor linguagem de programação?",
  "options": [
    "JavaScript",
    "Java",
    "PHP",
    "C#"
  ]
}

### Get poll by id
GET http://localhost:3333/polls/f2d3ef9e-f613-4fab-814b-3ab2c4d71110


### Vote on pool
POST http://localhost:3333/polls/f2d3ef9e-f613-4fab-814b-3ab2c4d71110/votes
Content-Type: application/json

{
  "pollOptionId": "9cc2ec51-7445-49e0-896c-b098d26cdac8"
}
