## Test Hello NLW
GET http://localhost:3333/hello


### Create poll
POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "Qual a melhor linguagem de programação?",
  "options": [
    "JavaScript",
    "Java",
    "PHP",
    "C#"
  ]
}
